services:
  - type: web
    name: portfolio
    env: python
    plan: free
    autoDeploy: true
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
      # --- crear superusuario si no existe (idempotente) ---
      python manage.py shell <<'PY'
from django.contrib.auth import get_user_model
import os
User = get_user_model()
u = os.environ.get('DJANGO_SUPERUSER_USERNAME', 'admin')
e = os.environ.get('DJANGO_SUPERUSER_EMAIL', 'you@example.com')
p = os.environ.get('DJANGO_SUPERUSER_PASSWORD', 'Admin123!2025')
if not User.objects.filter(username=u).exists():
    User.objects.create_superuser(u, e, p)
    print("Superuser created:", u)
else:
    print("Superuser already exists:", u)
PY
    startCommand: gunicorn portfolio.wsgi:application
    healthCheckPath: /
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: $RENDER_EXTERNAL_HOSTNAME
      - key: CSRF_TRUSTED_ORIGINS
        value: https://$RENDER_EXTERNAL_HOSTNAME
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
      # Si usas Cloudinary, descomenta y pon tu URL:
      - key: CLOUDINARY_URL
        value: cloudinary://894879829965278:FQZgePwXoPUyTKA8W7FBUu9BLQM@dgkhksmoh
      # Credenciales para crear el superusuario (se usan en el bloque de arriba)
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: you@example.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: Admin123!2025

databases:
  - name: portfolio-db
    plan: free
    ipAllowList: []
