services:
  - type: web
    name: portfolio
    env: python
    plan: free
    autoDeploy: true
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn portfolio.wsgi:application
    healthCheckPath: /
    envVars:
      # Seguridad / modo
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false

      # Hosts y CSRF: Render inyecta RENDER_EXTERNAL_HOSTNAME
      - key: ALLOWED_HOSTS
        value: $RENDER_EXTERNAL_HOSTNAME
      - key: CSRF_TRUSTED_ORIGINS
        value: https://$RENDER_EXTERNAL_HOSTNAME

      # Base de datos (Render rellenará el connectionString)
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString

    # Disco persistente para uploads del admin: MEDIA_ROOT = /opt/render/project/src/media
    disk:
      name: media
      mountPath: /opt/render/project/src/media
      sizeGB: 2

databases:
  - name: portfolio-db
    plan: free
    ipAllowList: []   # Solo accesible internamente desde tu servicio
