# Generated by Django 5.2.6 on 2025-09-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('image', models.URLField(blank=True)),
                ('summary', models.CharField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.CharField(blank=True, max_length=300)),
                ('external_link', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
